spring.application.name=02-MongoDB-SpringBoot
server.port=9011
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=SimpleDB
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
