spring.application.name=01-MongoDB-Reactive-BackPressure

server.port=9011
# MongoDB Connection Details
spring.data.mongodb.uri=mongodb://localhost:27017/hr1
# Server Tuning (Backpressure related)
# Limit the max number of concurrent HTTP connections
server.netty.max-connections=1000

# Logging to monitor reactive streams
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
