
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=HR1
mongo.uri=mongodb://localhost:27017/HR1

## MongoDB default port
dbport=27017

##MongoDB database name
dbname=HR1

server.port=8082