spring.application.name=03-MongoDB-Reactive-BackPressure
server.port=9011
# MongoDB Connection Details
spring.data.mongodb.database=SimpleDB1
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
# Server Tuning (Backpressure related)
# Limit the max number of concurrent HTTP connections
server.netty.max-connections=1000

# Logging to monitor reactive streams
logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate=DEBUG
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

