spring.application.name=67-SpringBoot-Security-3.x-OAuth2
server.port=8080
spring.security.oauth2.client.registration.github.client-id=Ov23liN0E9Ily26jwHTV
spring.security.oauth2.client.registration.github.client-secret=1edfe90a606c06f3f3fe97c04f318b6a5f97082c