spring.application.name=API-Gateway

spring.cloud.gateway.mvc.routes[0].id=HelloService
spring.cloud.gateway.mvc.routes[0].uri=lb://HelloService
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=helloapi/**

spring.cloud.gateway.mvc.routes[1].id=WelcomeService
spring.cloud.gateway.mvc.routes[1].uri=lb://WelcomeService
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=welcomeapi/**



server.port=9000

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/